extends: airbnb
parser: babel-eslint
env: 
  node: true,
  es6: true,
  browser: true
rules: 
  react/jsx-props-no-spreading: 0
  object-curly-newline: 0
  react/jsx-one-expression-per-line: 0
  import/no-unresolved: 0
  max-len: 0
  sort-imports: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  no-tabs: 1
  react/jsx-indent: 2
  indent: 0
  react/prop-types: 0
  react/sort-comp: 0
  react/jsx-max-props-per-line: 0
  class-methods-use-this: 0
  react/forbid-component-props: 0
  func-style: 0
  react/jsx-no-target-blank: 0 
  react/prefer-stateless-function: 0
  no-useless-constructor: 0
  linebreak-style: 0
  no-process-env: 0
  import/no-extraneous-dependencies: 0
  react/state-in-constructor: 0
  
  jsx-a11y/no-template-curly-in-string: 0
  jsx-a11y/no-noninteractive-element-interactions: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/click-events-have-key-events: 0
